
// This file has been generated by the GUI designer. Do not modify.
namespace MyFinance
{
	public partial class Home
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyFinance.Home
			this.Name = "MyFinance.Home";
			this.Title = global::Mono.Unix.Catalog.GetString ("Home");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
